### ISSUE TITLE
Getting some error for collection_name

### ISSUE THREAD

**Issue by vishal-nayak1** [qdrant/qdrant_demo#4]
I was trying to run this code but got this error for this line:
qdrant_client.recreate_collection(collection_name=COLLECTION_NAME, vector_size=vector_size)

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/vishal/qdrant/qdrant_demo/init_vector_search_index.py", line 33, in <module>
    qdrant_client.recreate_collection(
  File "/home/vishal/qdrant/venv/lib/python3.8/site-packages/qdrant_client/qdrant_client.py", line 246, in recreate_collection
    self.http.collections_api.update_collections(
  File "/home/vishal/qdrant/venv/lib/python3.8/site-packages/qdrant_openapi_client/api/collections_api.py", line 229, in update_collections
    return self._build_for_update_collections(
  File "/home/vishal/qdrant/venv/lib/python3.8/site-packages/qdrant_openapi_client/api/collections_api.py", line 185, in _build_for_update_collections
    return self.api_client.request(type_=m.InlineResponse2001, method="POST", url="/collections", json=body)
  File "/home/vishal/qdrant/venv/lib/python3.8/site-packages/qdrant_openapi_client/api_client.py", line 59, in request
    return self.send(request, type_)
  File "/home/vishal/qdrant/venv/lib/python3.8/site-packages/qdrant_openapi_client/api_client.py", line 82, in send
    raise UnexpectedResponse.for_response(response)
qdrant_openapi_client.exceptions.UnexpectedResponse: Unexpected Response: 422 (Unprocessable Entity)
Raw response content:
b'Json deserialize error: missing field `collection_name` at line 1 column 149'

Please help me to fix it?

**Comment by joein** [comment]
Hi, sorry for not responding :(

It seems like the method call was incorrect, it does not accept `vector_size`, instead it accepts `vectors_config`.

I am closing this issue since it is pretty old and this code does not exist in our repository
